---
title: "Alpha vs Beta: Optimal Qt"
author: "Charles Zheng"
date: "September 18, 2016"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Source

```{r}
source("alpha_vs_beta.R")
```

Plotting stuff
```{r}
plotit <- function(d, k) {
  qs <- qs_par(d, k)
  vals <- get_q_ints(qs, k)
  plot(qs, type = "l")
  title(paste0("d=", d, " k=", k, 
              " a=", formatC(vals[2], 2), 
              "  b=", formatC(vals[3], 2)))
}
```

## k = 2

Increasing $d$ increases MI ($\alpha$) and ABA ($\beta$).

```{r fig.height=3, fig.width=8, echo = FALSE}
par(mfrow= c(1, 3))
k <- 2
ds <- c(0.1, 0.5, 1.0, 2.0, 3.0, 6.0, 10, 20, 30)
for (d in ds) plotit(d, k)
```

## k = 3

```{r fig.height=3, fig.width=8, echo = FALSE}
par(mfrow= c(1, 3))
k <- 3
ds <- c(0.1, 0.5, 1.0, 2.0, 3.0, 6.0, 10, 20, 30)
for (d in ds) plotit(d, k)
```

## k = 10

```{r fig.height=3, fig.width=8, echo = FALSE}
par(mfrow= c(1, 3))
k <- 10
ds <- c(0.1, 0.5, 1.0, 2.0, 3.0, 6.0, 10, 20, 30)
for (d in ds) plotit(d, k)
```

